#!/usr/bin/env python3
"""mkdolblob.py — assemble a linked guest ELF into a DOL and emit it as a header.

The toolchain has no DOL packer, but the format is trivial: a 256-byte header of
section offset/address/size triples, then the section data. This reads the
guest's .text/.data from objcopy output and the entry point from nm.
"""
import struct, sys, re, subprocess, os

elf, textbin, entry_hex, result_hex, expected_hex, out = sys.argv[1:7]
# Optional: the symbol prefix, so more than one guest program can be built.
# Defaults to the original so existing callers are unaffected.
prefix = sys.argv[7] if len(sys.argv) > 7 else "dol"
entry = int(entry_hex, 16)

with open(textbin, "rb") as f:
    text = f.read()

TEXT_ADDR = 0x80003100          # where _start is linked
# One text section holds everything (we linked .text+.data together).
hdr = bytearray(0x100)
# text0: offset, address, size
struct.pack_into(">I", hdr, 0x00, 0x100)          # text0 file offset
struct.pack_into(">I", hdr, 0x48, TEXT_ADDR)      # text0 load address
struct.pack_into(">I", hdr, 0x90, len(text))      # text0 size
struct.pack_into(">I", hdr, 0xE0, entry)          # entry point
# bss: none needed for this program (table is const in .text)

dol = bytes(hdr) + text

with open(out, "w") as f:
    f.write("/* Generated by tools/mkdolblob.py -- a real GameCube DOL. */\n")
    guard = prefix.upper() + "_BLOB_H"
    f.write(f"#ifndef {guard}\n#define {guard}\n\n")
    f.write(f"#define {prefix.upper()}_RESULT_ADDR {result_hex}u\n")
    f.write(f"#define {prefix.upper()}_EXPECTED    {expected_hex}u\n\n")
    f.write(f"static const unsigned char {prefix}_blob[{len(dol)}] = {{\n")
    for i in range(0, len(dol), 12):
        f.write("    " + ", ".join(f"0x{b:02X}" for b in dol[i:i+12]) + ",\n")
    f.write("};\n\n#endif\n")
print(f"{out}: DOL {len(dol)} bytes, entry {entry:08x}, text {len(text)} bytes")
