#!/usr/bin/env python3
"""mkguestblob.py — turn linked guest PowerPC code into an embeddable header.

Reads the raw .text produced by objcopy plus the symbol table from nm, and
emits a header containing the code bytes and each function's guest address, so
the test harness has no runtime file dependency.

    mkguestblob.py <guestfns.bin> <nm_output.txt> <base_addr_hex> <out.h>
"""
import re
import sys


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    binpath, nmpath, base_hex, outpath = sys.argv[1:]
    base = int(base_hex, 16)

    with open(binpath, "rb") as f:
        code = f.read()

    syms = []
    with open(nmpath) as f:
        for line in f:
            m = re.match(r"^([0-9a-fA-F]+)\s+[Tt]\s+(gf_\w+)", line.strip())
            if m:
                syms.append((m.group(2), int(m.group(1), 16)))
    syms.sort(key=lambda s: s[1])

    with open(outpath, "w") as f:
        f.write("/* Generated by tools/mkguestblob.py -- do not edit.\n"
                " *\n"
                " * Real 32-bit PowerPC produced by the cross compiler at -O2 from\n"
                " * tests/guestcode/guestfns.c. The emulator runs this; the same source\n"
                " * compiled natively provides the expected answers.\n"
                " */\n")
        f.write("#ifndef GUEST_BLOB_H\n#define GUEST_BLOB_H\n\n")
        f.write(f"#define GUEST_CODE_BASE 0x{base:08X}u\n")
        f.write(f"#define GUEST_CODE_SIZE {len(code)}u\n\n")

        for name, addr in syms:
            f.write(f"#define GA_{name.upper()} 0x{addr:08X}u\n")
        f.write("\nstatic const unsigned char guest_code[GUEST_CODE_SIZE] = {\n")
        for i in range(0, len(code), 12):
            row = ", ".join(f"0x{b:02X}" for b in code[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n\n#endif\n")

    print(f"{outpath}: {len(code)} bytes, {len(syms)} functions")


if __name__ == "__main__":
    main()
