#!/usr/bin/env python3
"""wc_gen_calls.py -- generate the call layer for the statically recompiled game.

The translator emits `InvokeDirectCpu<0xADDR>(ctx)` for a direct guest `bl` and
`InvokeIndirectCpu(target, ctx)` for a computed one (bctrl/blrl). This writes:

  wc_calls.h    extern declarations for every translated function, plus a
                DECLARATION of the specialization for each -- cheap to parse,
                which matters when 11k translation units include it.
  wc_calls.cpp  the specialization definitions (one direct call each) and the
                sorted address->function table the indirect path binary-searches.

Native HLE overrides are applied by name: any address listed in the override
map dispatches to the native implementation instead of the translated body,
which is how the game's hardware-touching functions get replaced.

    wc_gen_calls.py <functions_dir> <out_dir> [overrides.txt]
"""
import os, re, sys

fdir, outdir = sys.argv[1], sys.argv[2]
overrides = {}
if len(sys.argv) > 3 and os.path.exists(sys.argv[3]):
    for ln in open(sys.argv[3]):
        ln = ln.split("#")[0].split()
        if len(ln) >= 2:
            overrides[int(ln[0], 16)] = ln[1]

# Addresses the scanner proved are computed at run time -- the set an indirect
# branch can land on. Read from the target list, NOT inferred from a `ptr_`
# name: 3,836 of the 6,108 targets also have names (every virtual method,
# every default callback), and inferring from the name left all of them out of
# the table. The game then called DefaultSwitchThreadCallback through a pointer
# and the port had no entry for it.
indirect = set()
_tgt = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                    "external", "mkwii-ntsc", "MAP_ntsc_full_targets.txt")
if os.path.exists(_tgt):
    for _ln in open(_tgt):
        _ln = _ln.strip()
        if _ln:
            indirect.add(int(_ln, 16))

addrs = sorted(int(m.group(1), 16)
               for f in os.listdir(fdir)
               for m in [re.fullmatch(r'func_([0-9A-Fa-f]{8})\.cpp', f)] if m)
os.makedirs(outdir, exist_ok=True)

with open(os.path.join(outdir, "wc_calls.h"), "w") as h:
    h.write('/* Generated by tools/wc_gen_calls.py -- do not edit. */\n#pragma once\n'
            '#include "ppc_runtime.h"\n\n'
            '/* A computed guest call: binary search of the address table. */\n'
            'void InvokeIndirectCpu(uint32_t target, CpuContext* ctx);\n\n'
            'template <uint32_t Target> void InvokeDirectCpu(CpuContext* ctx);\n\n')
    for a in addrs:
        h.write('extern "C" void func_%08X(CpuContext*);\n' % a)
    h.write("\n")
    for a in addrs:
        h.write('template <> void InvokeDirectCpu<0x%08Xu>(CpuContext*);\n' % a)

with open(os.path.join(outdir, "wc_calls.cpp"), "w") as c:
    c.write('/* Generated by tools/wc_gen_calls.py -- do not edit. */\n'
            '#include "wc_calls.h"\n#include <cstdint>\n\n')
    for name in sorted(set(overrides.values())):
        c.write('extern "C" void %s(CpuContext*);\n' % name)
    c.write("\n")
    for a in addrs:
        tgt = overrides.get(a, "func_%08X" % a)
        c.write('template <> void InvokeDirectCpu<0x%08Xu>(CpuContext* ctx) '
                '{ WC_DISPATCH(0x%08Xu, ctx); %s(ctx); }\n' % (a, a, tgt))
    # The indirect table names only addresses the guest can actually compute:
    # the scanner's targets plus the entry point. Naming every function instead
    # pins all of them against --gc-sections, and 5,865 of the 13,675 are dead
    # map entries no path reaches -- 15 MB of .text kept alive for nothing, on a
    # console where the budget is already tight (docs/PLAN.md §48).
    #
    # A target the scanner missed is not silent: it reaches WcUnresolvedCall,
    # which records and reports it, and the address can be fed back as a seed.
    tab = sorted(indirect | {0x800060A4}) if indirect else addrs
    c.write('\nnamespace {\nstruct Entry { uint32_t addr; void (*fn)(CpuContext*); };\n'
            'const Entry kTable[] = {\n')
    for a in tab:
        if a not in set(addrs):
            continue
        c.write('    { 0x%08Xu, %s },\n' % (a, overrides.get(a, "func_%08X" % a)))
    c.write('};\nconst unsigned kCount = sizeof kTable / sizeof kTable[0];\n}\n\n'
            'void WcUnresolvedCall(uint32_t target, CpuContext* ctx);\n\n'
            'void InvokeIndirectCpu(uint32_t target, CpuContext* ctx)\n{\n'
            '    unsigned lo = 0, hi = kCount;\n'
            '    while (lo < hi) {\n'
            '        unsigned mid = (lo + hi) / 2;\n'
            '        if (kTable[mid].addr == target)\n'
            '            { WC_DISPATCH(target, ctx); kTable[mid].fn(ctx); return; }\n'
            '        if (kTable[mid].addr < target) lo = mid + 1; else hi = mid;\n'
            '    }\n'
            '    WcUnresolvedCall(target, ctx);\n}\n')
print("wrote wc_calls.h / wc_calls.cpp for %d functions (%d native overrides)" % (len(addrs), len(overrides)))
