#!/usr/bin/env python3
"""wc_gen_fntable.py -- emit the function table the generic difftest walks.

    wc_gen_fntable.py <functions_dir> <out.cpp> [max]
"""
import os, re, sys
fdir, out = sys.argv[1], sys.argv[2]
# The third argument is either a COUNT (test the first N functions) or an
# explicit comma-separated list of guest addresses. Chasing a specific defect
# needs the second form: the functions that matter are rarely the first N, and
# building a table of 400 to reach one of them wastes a link.
sel = sys.argv[3] if len(sys.argv) > 3 else ""
addrs = sorted(int(m.group(1), 16)
               for f in os.listdir(fdir)
               for m in [re.fullmatch(r'func_([0-9A-Fa-f]{8})\.cpp', f)] if m)
if "," in sel or sel.lower().startswith("0x"):
    want = {int(x, 16) for x in sel.replace("0x", "").split(",") if x.strip()}
    have = set(addrs)
    missing = sorted(want - have)
    if missing:
        sys.stderr.write("no translation for: %s\n" %
                         " ".join("%08x" % a for a in missing))
    addrs = [a for a in addrs if a in want]
elif sel:
    addrs = addrs[:int(sel)]
import bisect
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
import symbolize as S
syms, sa = S.load()
with open(out, "w") as c:
    c.write('/* Generated by tools/wc_gen_fntable.py -- do not edit. */\n'
            '#include <cstdint>\nstruct WcCtxFwd;\n'
            'typedef union { uint64_t raw; double d; struct { float ps0, ps1; } paired; } PPC_FPR_T;\n'
            'struct WcCtx;\n'
            'typedef struct { uint32_t addr; void (*fn)(WcCtx*); const char* name; } WcFn;\n\n'
            'extern "C" {\n')
    for a in addrs:
        c.write('void func_%08X(WcCtx*);\n' % a)
    c.write('}\n\nextern "C" const WcFn g_wc_fns[] = {\n')
    for a in addrs:
        n = (S.name(a, syms, sa) or "?").split("+")[0][:26]
        c.write('    { 0x%08Xu, func_%08X, "%s" },\n' % (a, a, n.replace('"', '')))
    c.write('};\nextern "C" const unsigned g_wc_fn_count = sizeof g_wc_fns / sizeof g_wc_fns[0];\n')
print("wrote %s with %d functions" % (out, len(addrs)))
