#!/usr/bin/env python3
"""wc_hle_stubs.py -- inventory the native HLE surface the port must supply.

WiiCompiled binds a native implementation to a guest address by naming the
function with the address as a suffix (`GX__Begin_8016f0f0`). This reads that
catalogue out of its runtime, converts each PAL address to NTSC with the
piecewise delta (docs/PLAN.md §35), and writes the override map that
tools/wc_gen_calls.py consumes -- so the port can be brought up subsystem by
subsystem, with everything not yet implemented still running as translated
guest code.

    wc_hle_stubs.py <wiicompiled_runtime_src> <out_overrides.txt>
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import symbolize as S

src, out = sys.argv[1], sys.argv[2]
pat = re.compile(r'\b([A-Za-z_][A-Za-z0-9_]*)_(8[0-9a-f]{7})\s*\(')
found = {}
for root, _, files in os.walk(src):
    for f in files:
        if not f.endswith((".cpp", ".h")):
            continue
        sub = os.path.relpath(root, src).split(os.sep)[-1]
        for m in pat.finditer(open(os.path.join(root, f), errors="replace").read()):
            name, pal = m.group(1), int(m.group(2), 16)
            found.setdefault(pal, (name, sub))

rows = []
for pal, (name, sub) in sorted(found.items()):
    # symbolize maps NTSC->PAL; invert over the DOL text range by search.
    ntsc = None
    for cand in (pal, pal - 0x40, pal - 0xA0, pal - 0x384):
        if S.ntsc_to_pal(cand) == pal:
            ntsc = cand
            break
    rows.append((pal, ntsc, name, sub))

with open(out, "w") as fh:
    fh.write("# Native HLE overrides: NTSC address -> implementation.\n"
             "# Generated by tools/wc_hle_stubs.py from WiiCompiled's runtime.\n"
             "# Uncomment a row once the PS3 implementation exists; until then the\n"
             "# translated guest function runs, which is the correct fallback.\n")
    bysub = {}
    for pal, ntsc, name, sub in rows:
        bysub.setdefault(sub, []).append((pal, ntsc, name))
    for sub in sorted(bysub):
        fh.write("\n# ---- %s (%d) ----\n" % (sub, len(bysub[sub])))
        for pal, ntsc, name in bysub[sub]:
            if ntsc is None:
                fh.write("# UNMAPPED pal=%08x %s\n" % (pal, name))
            else:
                fh.write("# %08x %s   # pal %08x\n" % (ntsc, name, pal))
print("%d native entry points across %d subsystems -> %s"
      % (len(rows), len({r[3] for r in rows}), out))
for sub in sorted({r[3] for r in rows}):
    print("   %-10s %d" % (sub, sum(1 for r in rows if r[3] == sub)))
